### ISSUE TITLE
是否有设置可以开关自动转化文件？

### ISSUE THREAD

**Issue by Qyyxzz** [CherryHQ/cherry-studio#222]
有的带文件用起来会报错422 有没有办法可以开关

**Comment by kangfenmao** [comment]
> 有的带文件用起来会报错422 有没有办法可以开关

设置面板里面有开关

**Comment by kangfenmao** [comment]
<img width="325" alt="image" src="https://github.com/user-attachments/assets/92f232b9-127d-4ec8-8cc0-537156bca58c">
