### ISSUE TITLE
小程序中的Claude使用Google账号登录不上

### ISSUE THREAD

**Issue by Johnny0x38E** [CherryHQ/cherry-studio#31]
小程序中的Claude使用Google账号登录不上

error: There was an error logging you in. If the problem persistsfor assistance.

**Comment by kangfenmao** [comment]
收到，下个版本修复

**Comment by kangfenmao** [comment]
https://github.com/kangfenmao/cherry-studio/releases/tag/v0.6.1

更新然后验证一下 @johnnyh5
