### ISSUE TITLE
[问题]: 在哪里调整API的更多参数？例如presence_penalty

### ISSUE THREAD

**Issue by oyasumiaiko** [CherryHQ/cherry-studio#555]
### 您的问题

在哪里可以调整除了temperature以外的API参数？presence_penalty，top_p等，现在在UI里没找到对应设置
如有可能希望能自定义输入字段名和对应数值

### 相关背景

有些模型默认回复风格需要调整。仅调整temperature不足以满足回复需求。

### 优先级

中 (希望尽快得到答复)

**Comment by kangfenmao** [comment]
![image](https://github.com/user-attachments/assets/aa877351-b2b2-483e-b5a4-e091e28317f3)

目前只有这些设置可以配置

**Comment by kangfenmao** [comment]
我去修改一下
