### ISSUE TITLE
[功能]: 添加模型中可以设置其他厂商

### ISSUE THREAD

**Issue by sjhsbhqf** [CherryHQ/cherry-studio#586]
### 您的功能建议是否与某个问题相关?

![image](https://github.com/user-attachments/assets/bc641077-9ab2-43b2-9afc-35ccbed575f9)

在linuxdo中有一个4chat的公益服务，由于他们说这个https://api.4chat.me/v1/models需要用siliconflow的类型

所以我在原来官方的siliconflow的类型模型里面能够填入这个api key和host，并且能check成功。

然而我不想在官方的siliconflow的类型模型里面填入，因为容易冲突。

### 请描述您希望实现的解决方案

希望在add模型提供商的那个type里面，不仅仅是openai、Gemini、Anthropic这3种

![image](https://github.com/user-attachments/assets/6b38ecda-bf87-426f-9ad7-cf858d108280)

还包括其他的国产api厂商

### 请描述您考虑过的其他方案

已描述

### 其他补充信息

已描述

**Comment by IwfWcf** [comment]
类型那里你选 openai 就行了，这里其实是让你选 api 的格式类型

**Comment by sjhsbhqf** [comment]
> 类型那里你选 openai 就行了，这里其实是让你选 api 的格式类型

我选openai在model里面没有看到任何模型....

![image](https://github.com/user-attachments/assets/b12fe793-0b93-44eb-817a-4df33608aa5c)

**Comment by IwfWcf** [comment]
> > 类型那里你选 openai 就行了，这里其实是让你选 api 的格式类型
> 
> 我选 openai 在 model 里面没有看到任何模型....
> 
> ![image](https://private-user-images.githubusercontent.com/41407099/399328889-b12fe793-0b93-44eb-817a-4df33608aa5c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU1NzUzOTQsIm5iZiI6MTczNTU3NTA5NCwicGF0aCI6Ii80MTQwNzA5OS8zOTkzMjg4ODktYjEyZmU3OTMtMGI5My00NGViLTgxN2EtNGRmMzM2MDhhYTVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjMwVDE2MTEzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY4MGJlODc2ZWUwMGRjZTgyZjkyMzdkMmMyNjIzYjc4ZWYxNTQ5MTExY2ZkNzEwMjhlOTMwN2UyZWNiYjAxYzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Du9u7aRnLQ-iuaK9towhn40JxuOwtcN-1Mk0uJwRF4Y)

api host 填 https://api.4chat.me

**Comment by kangfenmao** [comment]
API 地址填错了，参考 @IwfWcf 的回答

**Comment by sjhsbhqf** [comment]
@IwfWcf 
这样填的话，model里面没有看到国产的模型

![image](https://github.com/user-attachments/assets/41af7ea4-6164-4340-a29e-ea488b5e50e5)

**Comment by ForstJean** [comment]
“管理”的模型不一定全，可以点击“添加”加上你在提供商的模型列表里想用的模型id，只要能连通就行

**Comment by IwfWcf** [comment]
> @IwfWcf 这样填的话，model 里面没有看到国产的模型 ![image](https://private-user-images.githubusercontent.com/41407099/399329505-27e70ce9-f3b5-4350-8dcb-1b3a163ec145.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU1NzU2NTEsIm5iZiI6MTczNTU3NTM1MSwicGF0aCI6Ii80MTQwNzA5OS8zOTkzMjk1MDUtMjdlNzBjZTktZjNiNS00MzUwLThkY2ItMWIzYTE2M2VjMTQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjMwVDE2MTU1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE4ODNkNTg5YTVjMjg1ZjE2YWZhYWEwZTlkOWVlYzg0YTNiN2JiOGUyYzQwZGU3NGNiZGZiZDk5ODQyMGEwNmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.PmVxKxCQhHYT5Jqmmwhg5DDE4bUpBJEgdKqsvM_6nTs)
> 
> ![image](https://private-user-images.githubusercontent.com/41407099/399329448-41af7ea4-6164-4340-a29e-ea488b5e50e5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU1NzU2NTEsIm5iZiI6MTczNTU3NTM1MSwicGF0aCI6Ii80MTQwNzA5OS8zOTkzMjk0NDgtNDFhZjdlYTQtNjE2NC00MzQwLWEyOWUtZWE0ODhiNWU1MGU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjMwVDE2MTU1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWExZThhNzI1YTc1Y2VmOTBlY2U0Zjg4NGJlOTc4N2QzZmE0NWNjZTBlZmU2MjNiNjMzNjIwMDAxNzk0ODc2M2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.GUwMm4cI-4QkcPzeeIOdybh-_Wr6UnpGRRm3n4NMcLs)

那是因为 4chat 这个本来就不支持国产的模型啊……
