### ISSUE TITLE
[问题]: “智能体”实现方式

### ISSUE THREAD

**Issue by vva1024** [CherryHQ/cherry-studio#595]
### 您的问题

作者您好，很优秀的一款应用，首先表示感谢🙏！

我在设置自己的 prompt 时候有一些疑问：

在这里设置的提示词在接口调用时，是以 system prompt 的形式生效，还是作为普通的 user prompt 发挥作用呢？

<img width="740" alt="image" src="https://github.com/user-attachments/assets/fe650543-c40e-43ca-bec7-fa0ea687aef4" />

### 优先级

低 (有空再看)

**Comment by kangfenmao** [comment]
系统提示词，用户提示词是你输入框输入的内容
